/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package email.java;

import email.java.config.LoadConfig;
import email.java.process.EmailProcess;

public class App {

    public static void main(String[] args) {

        LoadConfig.getInstance().loadProperties();
        EmailProcess.process(LoadConfig.getInstance().getPathEmail());

    }
}
